server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.controller

nacos:
  config:
    server-addr: 127.0.0.1:8848
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
#  security:
#    user:
#      name: admin
#      password: admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 强制控制台输出SQL

zookeeper:
  connect-string: localhost:2181
  session-timeout: 5000

